# Example pipeline of how to leverage an Azure Key Vault to retrieve secrets for usage within the pipeline.

trigger:
- main

pool: 'CycleReady ScaleSet - Windows Server 2019'

steps:
- task: AzureKeyVault@2
  inputs:
    #azureSubscription: 'Cycle SaaS - Dev - Managed Identity'
    azureSubscription: 'Cycle SaaS - Dev(bf75aa33-e54f-419f-b36d-69a6f1a9d84b)'
    KeyVaultName: 'kv-development-5itM'
    # Using a wildcard will pull all secrets, you should use filters.
    # SecretsFilter: '*'
    SecretsFilter: 'CYCLE-UM-MONGO-URI-development'
    RunAsPreJob: true

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Set-Content -Path .\secret.txt -Value '$(CYCLE-UM-MONGO-URI-development)'

- task: CopyFiles@2
  inputs:
    Contents: secret.txt
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'