# Run this: docker-compose up --abort-on-container-exit
services:
  cycle-connection-test:
    image: "cyclelabs/cycle-cli:latest"
    #image: "cycledev.azurecr.io/cycledev/cycle:latest"
    shm_size: 2g
    volumes:
      - .:/code
    env_file:
      - secrets.env
    # environment:
    #   PW_ORACLE_DB: ${PW_ORACLE_DB}
    #   PW_SQL_DB: ${PW_SQL_DB}
    #   PW_DB2: ${PW_DB2}
    #   PW_MYSQL: ${PW_MYSQL}
    #   PW_SQL14_DB: ${PW_SQL14_DB}
    #   PW_TELNET: ${PW_TELNET}
    #   PW_MOCA: ${PW_MOCA}
    #   PW_AZURESQL: ${PW_AZURESQL}
    #   UN_AZURESQL: ${UN_AZURESQL}
    #   PW_OPENSSH: ${PW_OPENSSH}
    #   AUTH_TOKEN: ${AUTH_TOKEN}
    #   CI_CYCLE_AUTH: ${CI_CYCLE_AUTH}
    #   CI_CYCLE_AUTH_SECRET: ${CI_CYCLE_AUTH_SECRET}

    depends_on:
      - "chrome-connection-test"
    command: ["--clientid", "${CI_CYCLE_AUTH}", "--client-credential", "${CI_CYCLE_AUTH_SECRET}", "-p", "/code", "combined/conf-file-cycle-connection-test.feature"]


  chrome-connection-test:
    image: "selenium/standalone-chrome"
    environment:
      - CHROME_OPTS=--no-sandbox --disable-dev-shm-usage --headless
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4445:4444"
    hostname: chrome
    privileged: true
    shm_size: 2g
