version: "3.9"
services:
  cycle-api-test:
    image: "cycledev.azurecr.io/cycledev/cycle:latest"
    shm_size: 2g
    volumes:
      - .:/code
    command: ["--token", "${AUTH_TOKEN}", "-p", "/code", "combined/api-test.feature"]
    environment:
      AUTH_TOKEN: ${AUTH_TOKEN}
      MAPS_API_KEY: ${MAPS_API_KEY}