# Run this: docker-compose up --abort-on-container-exit
version: "3.9"
services:
  # cycle-web-test:
  #   ## Used for M1 procs
  #   #image: "cycledev.azurecr.io/cycledev/cycle:0.0.2"
  #   image: "cycledev.azurecr.io/cycledev/cycle-ubu:0.0.3"
  #   volumes:
  #     - .:/code
  #   environment:
  #     WAIT_HOSTS: chrome:4444
  #     GROCER_USER: "courtney.montgomery@cyclelabs.io"
  #     GROCER_PASS: hunter13
  #   depends_on:
  #     - "chrome"
  #   command: bash -c "/wait && /home/cycle/cycle-cli -p /code combined/combined.feature"
  cycle-connection-test:
    image: "cycledev.azurecr.io/cycledev/cycle-ubu:0.0.3"
    volumes:
      - .:/code
    environment:
      WAIT_HOSTS: chrome:4444
      PW_ORACLE_DB: ${PW_ORACLE_DB}
      PW_SQL_DB: ${PW_SQL_DB}
      PW_DB2: ${PW_DB2}
      PW_MYSQL: ${PW_MYSQL}
      PW_SQL14_DB: ${PW_SQL14_DB}
      PW_TELNET: ${PW_TELNET}
      PW_MOCA: ${PW_MOCA}
      PW_AZURESQL: ${PW_AZURESQL}
      PW_OPENSSH: ${PW_OPENSSH}
    depends_on:
      - "chrome"
    command: bash -c "/wait && /home/cycle/cycle-cli -p /code combined/conf-file-cycle-connection-test.feature"
  cycle-api-test:
    image: "cycledev.azurecr.io/cycledev/cycle-ubu:0.0.3"
    volumes:
      - .:/code
    command: bash -c "/wait && /home/cycle/cycle-cli -p /code combined/api-test.feature"
  cycle-browser-test:
    image: "cycledev.azurecr.io/cycledev/cycle-ubu:0.0.3"
    volumes:
      - .:/code
    depends_on:
      - "chrome"
      - "edge"
      # - "firefox"
    command: bash -c "/wait && /home/cycle/cycle-cli -p /code combined/browser-test.feature"
  selenium-hub:
      image: selenium/hub
      container_name: selenium-hub
      ports:
        - "4444:4444"
  chrome:
    image: selenium/node-chrome
    # volumes:
    #   - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  edge:
    image: selenium/node-edge
    # volumes:
    #   - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

