services:
  cycle-browser-test-edge:
    image: "cyclelabs/cycle-cli:latest"
    #image: "cycledev.azurecr.io/cycledev/cycle:latest"
    shm_size: 2g
    volumes:
      - .:/code
    depends_on:
      - "edge"
    command: ["--clientid", "${DOCKERIZED_CYCLE_APP_ID}", "--client-credential", "${DOCKERIZED_CYCLE_APP_SECRET}", "-p", "/code", "combined/grocerio-browser-test-edge.feature"]
    environment:
      PW_ORACLE_DB: ${PW_ORACLE_DB}
      PW_SQL_DB: ${PW_SQL_DB}
      PW_DB2: ${PW_DB2}
      PW_MYSQL: ${PW_MYSQL}
      PW_SQL14_DB: ${PW_SQL14_DB}
      PW_TELNET: ${PW_TELNET}
      PW_MOCA: ${PW_MOCA}
      PW_AZURESQL: ${PW_AZURESQL}
      UN_AZURESQL: ${UN_AZURESQL}
      PW_OPENSSH: ${PW_OPENSSH}
      AUTH_TOKEN: ${AUTH_TOKEN}
      MAPS_API_KEY: ${MAPS_API_KEY}
      DOCKERIZED_CYCLE_APP_ID: ${CI_CYCLE_AUTH}
      DOCKERIZED_CYCLE_APP_SECRET: ${CI_CYCLE_AUTH_SECRET}

  edge:
    image: "selenium/standalone-edge"
    environment:
      - EDGE_OPTS=--headless --no-sandbox --disable-dev-shm-usage
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "5555:4444"
    hostname: edge
    privileged: true
    shm_size: 2g
