# Run this: docker-compose up --abort-on-container-exit
services:
  cycle-connection-test:
    image: "cycledev.azurecr.io/cycledev/cycle:20241210.1"
    shm_size: 2g
    volumes:
      - .:/code
    environment:
      WAIT_HOSTS: chrome:4444
      PW_ORACLE_DB: ${PW_ORACLE_DB}
      PW_SQL_DB: ${PW_SQL_DB}
      PW_DB2: ${PW_DB2}
      PW_MYSQL: ${PW_MYSQL}
      PW_SQL14_DB: ${PW_SQL14_DB}
      PW_TELNET: ${PW_TELNET}
      PW_MOCA: ${PW_MOCA}
      PW_AZURESQL: ${PW_AZURESQL}
      PW_OPENSSH: ${PW_OPENSSH}
      AUTH_TOKEN: ${AUTH_TOKEN}
      MAPS_API_KEY: ${MAPS_API_KEY}
      DOCKERIZED_CYCLE_APP_ID: ${DOCKERIZED_CYCLE_APP_ID}
      DOCKERIZED_CYCLE_APP_SECRET: ${DOCKERIZED_CYCLE_APP_SECRET}
    depends_on:
      - "chrome-connection-test"
    command: ["--clientid", "${DOCKERIZED_CYCLE_APP_ID}", "--client-credential", "${DOCKERIZED_CYCLE_APP_SECRET}", "-p", "/code", "combined/conf-file-cycle-connection-test.feature"]


  chrome-connection-test:
    image: "selenium/standalone-chrome"
    environment:
      - CHROME_OPTS=--no-sandbox --disable-dev-shm-usage --headless
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4445:4444"
    hostname: chrome
    privileged: true
    shm_size: 2g