# Buildspec reference: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

# Specifies the buildspec version (0.2 is the latest as of 02/02/2024).
version: 0.2

phases:
  pre_build:
    commands:
      - echo "Install Azure CLI"
      - curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - echo "Logging into AKV and exporting secrets into variables"
      - az login --service-principal --username $AKV_UN --password $AKV_PW --tenant $AKV_TENANT
      - export PW_CYCLEDEV_ACR=$(az keyvault secret show --vault-name kv-development-5itM --name PW-CYCLEDEV-ACR --query 'value' --output tsv)
      - export MAPS_API_KEY=$(az keyvault secret show --vault-name kv-development-5itM --name GOOGLE-MAPS-API-KEY --query 'value' --output tsv)
      - export AUTH_TOKEN=$(az keyvault secret show --vault-name kv-development-5itM --name CYCLE-AUTH-TOKEN-072623 --query 'value' --output tsv)
      - echo "Logging into ACR and preparing Docker"
      - docker login cycledev.azurecr.io -u cycledev -p $PW_CYCLEDEV_ACR
      - docker-compose -f docker-compose-api-test-codebuild.yml build --build-arg maps_api_key='$MAPS_API_KEY' --build-arg auth_token='$AUTH_TOKEN'
      - docker-compose -f docker-compose-api-test-codebuild.yml up -d --remove-orphans

  build:
    commands:
      - echo "Executing Cycle API Test"
      - docker-compose logs -f cycle-api-test

  post_build:
    commands:
      - echo "Tearing down Docker"
      - docker-compose -f docker-compose-api-test-codebuild.yml down -v