# Buildspec reference: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

# Specifies the buildspec version (0.2 is the latest as of 02/02/2024).
version: 0.2

phases:
  pre_build:
    commands:
      - echo "Install Azure CLI"
      - curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - echo "Logging into AKV and exporting secrets into variables"
      - az login --service-principal --username $AKV_UN --password $AKV_PW --tenant $AKV_TENANT
      - export PW_ORACLE_DB=$(az keyvault secret show --vault-name kv-development-5itM --name PW-ORACLE-DB --query 'value' --output tsv)
      - export PW_SQL_DB=$(az keyvault secret show --vault-name kv-development-5itM --name PW-SQL-DB --query 'value' --output tsv)
      - export PW_SQL14_DB=$(az keyvault secret show --vault-name kv-development-5itM --name PW-SQL14-DB --query 'value' --output tsv)
      - export PW_DB2=$(az keyvault secret show --vault-name kv-development-5itM --name PW-DB2 --query 'value' --output tsv)
      - export PW_MYSQL=$(az keyvault secret show --vault-name kv-development-5itM --name PW-MYSQL --query 'value' --output tsv)
      - export PW_TELNET=$(az keyvault secret show --vault-name kv-development-5itM --name PW-TELNET --query 'value' --output tsv)
      - export PW_OPENSSH=$(az keyvault secret show --vault-name kv-development-5itM --name PW-OPENSSH --query 'value' --output tsv)
      - export PW_MOCA=$(az keyvault secret show --vault-name kv-development-5itM --name PW-MOCA --query 'value' --output tsv)
      - export PW_AZURESQL=$(az keyvault secret show --vault-name kv-development-5itM --name PW-AZURESQL --query 'value' --output tsv)- export PW_CYCLEDEV_ACR=$(az keyvault secret show --vault-name kv-development-5itM --name PW-CYCLEDEV-ACR --query 'value' --output tsv)
      - export MAPS_API_KEY=$(az keyvault secret show --vault-name kv-development-5itM --name GOOGLE-MAPS-API-KEY --query 'value' --output tsv)
      - export AUTH_TOKEN=$(az keyvault secret show --vault-name kv-development-5itM --name CYCLE-AUTH-TOKEN-072623 --query 'value' --output tsv)
      - echo "Logging into ACR and preparing Docker"
      - docker login cycledev.azurecr.io -u cycledev -p $PW_CYCLEDEV_ACR
      - docker-compose -f docker-compose-edge-test-codebuild.yml build --build-arg pw_oracle_db='$PW_ORACLE_DB' --build-arg pw_sql_db='$PW_SQL_DB' --build-arg pw_sql14_db='$PW_SQL14_DB' --build-arg pw_db2='$PW_DB2' --build-arg pw_mysql='$PW_MYSQL' --build-arg pw_telnet='$PW_TELNET' --build-arg pw_openssh='$PW_OPENSSH' --build-arg pw_moca='$PW_MOCA' --build-arg pw_azuresql='$PW_AZURESQL' --build-arg maps_api_key='$MAPS_API_KEY' --build-arg auth_token='$AUTH_TOKEN'
      - docker-compose -f docker-compose-edge-test-codebuild.yml up -d --remove-orphans

  build:
    commands:
      - echo "Executing Edge Test"
      - docker-compose logs -f cycle-browser-test-edge

  post_build:
    commands:
      - echo "Tearing down Docker"
      - docker-compose -f docker-compose-edge-test-codebuild.yml down -v